# Week 6 Section 5 Python HW
## NumPy and Pandas

1. **What does Pandas stand for?** Panel data OR Python Data analysis
2. **What are the 2 collections used in Pandas?** Dataframes & Series
3. **Name 4 things Pandas can do for us.**
    + Load
    + Manipulate
    + Prepare
    + Model
    + Analyze
4. **To permanently sort a DataFrame, which keyword should one use with the df.sort() method?** IDK, 'inplace=true' is used to edit OG file, if not used or False then a new file is created. Is this what this is asking? If so prob need to reword it.
5. **What is a CSV?** A comma seperated file: that contains plain text and is a well known format that can be read by everyone including pandas.
6. **When cleaning data what values do we not like in our data?**
    + Missing Values
    + Duplicate Data
    + Formating/Typos
        1. Capitalization
        2. Varied Date formats
        3. Typographical errors AKA Misspellings
    + Incorrect Data Types
    + Structural Errors

In [3]:
import numpy as np

import pandas as pd


In [28]:
# 7.Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

aArray  = np.array(
                        [
                            [[33, 44],[55, 66],[77, 88]],
                            [[33, 44],[55, 66],[77, 88]]
                        ]
                   )
print(aArray)

[[[33 44]
  [55 66]
  [77 88]]

 [[33 44]
  [55 66]
  [77 88]]]


In [36]:
# 8.Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

testlp = np.linspace(0, 20, num=6)
print("test linspace array \n", testlp)

test linspace array 
 [ 0.  4.  8. 12. 16. 20.]


In [38]:
# 9.Make a Deep Copy of the above array
import copy

tlp1 = [[0,  4,  8, 12, 16, 20]]
tlp2 = copy.deepcopy(tlp1)

print(tlp1)

print("Copied array example \n", tlp2)



[[0, 4, 8, 12, 16, 20]]
Copied array example 
 [[0, 4, 8, 12, 16, 20]]


In [10]:
#****This was taught in 5.1 and we skipped that section***
# 10.Concatenate these 3 arrays into a new array named 'newArray'...

#         ([[25, 16]])
#         ([[11, 2], [13, 4]])
#         ([[7, 81], [5, 6], [11, 12]])
cc1 = np.array([[25, 16]])
cc2 = np.array([[11, 2], [13, 4]])
cc3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((cc3, cc2, cc1), axis=0)
print("Print newArray...", newArray)


Print newArray... [[ 7 81]
 [ 5  6]
 [11 12]
 [11  2]
 [13  4]
 [25 16]]


In [ ]:
#****This was taught in 5.1 and we skipped that section***
# 11.Sort 'newArray' in order into 'sortedArray'
# print("Print newArray...", newArray)

print(np.sort(newArray))


[[ 7 81]
 [ 5  6]
 [11 12]
 [ 2 11]
 [ 4 13]
 [16 25]]


In [17]:
#****This was taught in 5.1 and we skipped that section***
# # 12.Unpack the array tuples from the above 'reshapedArray' 
# into 4 well named variables. Print the 4 variables.
test51 = ([ [7, 81],
            [5, 6],
            [11, 12],
            [2, 11],
            [4, 13],
            [16, 25]
            ])

a, b, c, d, e, f = test51

print("a = ", a)
print("b = ", b)
print("c = ", c)


a =  [7, 81]
b =  [5, 6]
c =  [11, 12]


In [ ]:
#****This was taught in 5.1 and we skipped that section***
# 13.Combined and sort the following arrays into one called 'comboArray' ...

#     one = ([10, 11, 12, 13, 14, 15, 16, 17])
#     two = ([20, 21, 22, 23, 24, 25, 26, 27])
#     three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#****This was taught in 5.1 and we skipped that section***
# 14. Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element
# print sec2 - all elements from the 3rd element to the last
# print sec3 - all elements from the 4th to the 14th elements
# print sec4 - the last 6 elements
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
# print sec6 - from #20 every even element to the end
# print sec7 - from the last element moving forward, every 5th element.

In [6]:
# 15. Using Series, create a DataFrame that looks like this:

# Ingredients	Quantity	Unit
# Flour	4	cups
# Milk	1	cup
# Eggs	2	large
# Spam	1	can
# Name: Dinner, dtype: object

Ingredients = pd.Series(['Flour','Milk', 'Eggs', 'Spam'], name= 'Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name= 'Quantity')
Unit = pd.Series(['cups', 'cup', 'large', 'can'], name= 'Unit')

df = pd.concat([Ingredients, Quantity, Unit], axis=1)
print(df)


  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [ ]:
# 16.Take this data and create a DataFrame named studentData

studentdata =    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
SD = pd.DataFrame(studentdata)
print("studentdata...\n", SD )



studentdata...
       Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [ ]:
# 17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
dessert = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
SD['Dessert'] = dessert
print("studentdata...\n", SD )


studentdata...
       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Dessert  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [23]:

# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
SD.sort_values(by = ['Name'])
print(SD)

SD.sort_values(by = ['address'], inplace=True)
print(SD)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Dessert  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  
      Name  Height Qualification  address  Age        Pets           sport  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Dessert  
2       waffels  
3  Carrot Halwa  
0     ice cream  
1  Cashew Fudge  


In [ ]:
# 19.Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

#     df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
# 20.(A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.